FORMAT: 1A

# operator api
operator is a central server that enables various frontends to work with tails. operator manages all the low level details such as hitting up the database, interacting with the storage (through the storage microservice)

# Group project
this section groups project resources

## Post [/project/list]
a project is a project thingy

+ Model (application/json)

  ```json
  {
      "meta": {
          "code": 200,
      },
      "data": {
        "id": "1", // note this is a string
        "user": {
          ...
        },
        "created_at": "2012-07-16T17:25:47Z",
      }
  }
  ```

### get project list [GET]
returns a list of projects

+ Response 200

    [Post][]

## Runtime [/project/view]
view your posts

+ Model (application/json)

  ```js
  {
    "data": [
      {
        "id": "1", // note this is a string
        ...
      }
    ],
    "meta": {
      "code": 200,
    }
  }
  ```

### project view [POST]
view a single project

+ Request

  [Post][]

+ Response 201

  [Post][]

### Retrieve all Posts [GET]
Retrieves all posts.

+ Response 200

  [Runtime][]

## create message [/project/delete]
create a message

+ Model (application/json)

  ```json
  {
      "meta": {
          "code": 200,
      },
      "data": {
        "id": "1", // note this is a string
        "user": {
          ...
        },
        "created_at": "2012-07-16T17:25:47Z",
      }
  }
  ```

### create a message [GET]
stop

+ Response 200

  [Post][]
